version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = false
s3_bucket = "nouscloud-sam-deployment-bucket"
s3_prefix = "sam-app"
region = "ap-south-1"
profile = "arnab_power"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "GoogleApiKey=AIzaSyDANUocPulbWEpEuEoVX5cgnaWA0v3FxnQ"
