AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI chatbot backend on Lambda + API Gateway

Parameters:
  GoogleApiKey:
    Type: String
    Description: Google Gemini API Key
    NoEcho: true

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: server.handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          GOOGLE_API_KEY: !Ref GoogleApiKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/chatbot/send
            Method: post
